### ISSUE TITLE
`/insomnia status` always returns 1, regardless of actual insomnia status

### ISSUE THREAD

**Issue by James103** [were491/freedom-of-insomnia#1]
https://github.com/were491/freedom-of-insomnia/blob/c1f3a3e05df9d59720fbc84b3cb23e6cc994b4e0/src/main/java/com/rha1117/freedomofinsomnia/InsomniaCommand.java#L46-L51
Instead of the above code meaning that `/insomnia status` always returns 1, I would suggest changing it so the command returns 0 if insomnia is disabled, and 1 if insomnia is enabled. This would allow datapacks to automatically disable or re-enable insomnia (phantom spawning) for a player if certain conditions are met.
```java
private int displayStatus(CommandContext<ServerCommandSource> context) throws CommandSyntaxException {
	if (((CommandMixinInterface) context.getSource().getPlayer()).getInsomniaDisabled()) {
		context.getSource().sendFeedback(new LiteralText("Insomnia is currently disabled.").formatted(Formatting.RED), false);
		return 0;
	} else {
		context.getSource().sendFeedback(new LiteralText("Insomnia is currently enabled.").formatted(Formatting.GREEN), false);
		return 1;
	}
}
```

**Comment by were491** [comment]
ok i think i fixed it

**Comment by James103** [comment]
I believe you here. It looks like you even applied the exact same diff that I was looking for!

**Comment by were491** [comment]
yeah, i copy pasted it xD

but i changed a ton of stuff on my system in between the last time i touched this and now so i'm not sure if i accidentally broke anything else in the meantime.
