### ISSUE TITLE
Port mod to 1.20.1

### ISSUE THREAD

**Issue by ArkoSammy12** [were491/freedom-of-insomnia#2]
This mod is pretty great for community SMP servers. I myself used to use it in mine, but ever since we updated to 1.20, we can't use it anymore. It would be nice of the mod could get updated as well.

**Comment by ArkoSammy12** [comment]
I have  made a [pull request](https://github.com/were491/freedom-of-insomnia/pull/3) which ports the mod straight to 1.20.1 if anyone want to use it

**Comment by were491** [comment]
Sorry I didn't see this until now (I haven't opened GitHub since years ago). Thanks for updating it, because I actually needed this when one of my friends asked if I wanted to hop on Minecraft again. I'll redirect others to use your mod from now on if that's okay.
